// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: indicator_app

#include "../ui.h"

void ui_demoScreen_screen_init(void)
{
ui_demoScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_demoScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_demoScreen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_demoScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_keyboard = lv_keyboard_create(ui_demoScreen);
lv_obj_set_width( ui_keyboard, 483);
lv_obj_set_height( ui_keyboard, 178);
lv_obj_set_x( ui_keyboard, 0 );
lv_obj_set_y( ui_keyboard, 153 );
lv_obj_set_align( ui_keyboard, LV_ALIGN_CENTER );

ui_letsGetStarted = lv_label_create(ui_demoScreen);
lv_obj_set_width( ui_letsGetStarted, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_letsGetStarted, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_letsGetStarted, -56 );
lv_obj_set_y( ui_letsGetStarted, -111 );
lv_obj_set_align( ui_letsGetStarted, LV_ALIGN_CENTER );
lv_label_set_text(ui_letsGetStarted,"Let's get started!\n\nPlease enter a name:");
lv_obj_set_style_text_color(ui_letsGetStarted, lv_color_hex(0x0F71BE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_letsGetStarted, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_letsGetStarted, &lv_font_montserrat_30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_enterNameArea = lv_textarea_create(ui_demoScreen);
lv_obj_set_width( ui_enterNameArea, 399);
lv_obj_set_height( ui_enterNameArea, LV_SIZE_CONTENT);   /// 70
lv_obj_set_x( ui_enterNameArea, -18 );
lv_obj_set_y( ui_enterNameArea, -14 );
lv_obj_set_align( ui_enterNameArea, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_enterNameArea,"Your name...");
lv_textarea_set_one_line(ui_enterNameArea,true);
lv_obj_set_style_text_font(ui_enterNameArea, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_enterNameArea, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_enterNameArea, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(ui_enterNameArea, lv_color_hex(0xD8D8D8), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_enterNameArea, 255, LV_PART_SELECTED| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_enterNameArea, &lv_font_montserrat_20, LV_PART_SELECTED| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(ui_enterNameArea, lv_color_hex(0xD8D8D8), LV_PART_CURSOR | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_enterNameArea, 255, LV_PART_CURSOR| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_enterNameArea, &lv_font_montserrat_20, LV_PART_CURSOR| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(ui_enterNameArea, lv_color_hex(0x8F8F8F), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_enterNameArea, 255, LV_PART_TEXTAREA_PLACEHOLDER| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_enterNameArea, &lv_font_montserrat_20, LV_PART_TEXTAREA_PLACEHOLDER| LV_STATE_DEFAULT);

lv_keyboard_set_textarea(ui_keyboard,ui_enterNameArea);
lv_obj_add_event_cb(ui_keyboard, ui_event_keyboard, LV_EVENT_ALL, NULL);

}
