// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: indicator_app

#include "../ui.h"

void ui_demoScreen2_screen_init(void)
{
ui_demoScreen2 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_demoScreen2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_add_event_cb(ui_demoScreen2, ui_event_demoScreen2, LV_EVENT_ALL, NULL);

}
