// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: indicator_app

#include "../ui.h"

void ui_demoScreen8_screen_init(void)
{
ui_demoScreen8 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_demoScreen8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_demoScreen8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_demoScreen8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_cloudComputing = lv_label_create(ui_demoScreen8);
lv_obj_set_width( ui_cloudComputing, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_cloudComputing, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_cloudComputing, 1 );
lv_obj_set_y( ui_cloudComputing, -53 );
lv_obj_set_align( ui_cloudComputing, LV_ALIGN_CENTER );
lv_label_set_text(ui_cloudComputing,"Great! Have you heard of\ncloud computing before?");
lv_obj_set_style_text_color(ui_cloudComputing, lv_color_hex(0x0F71BE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_cloudComputing, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_cloudComputing, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_cloudComputing, &lv_font_montserrat_30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_yesButton = lv_btn_create(ui_demoScreen8);
lv_obj_set_width( ui_yesButton, 100);
lv_obj_set_height( ui_yesButton, 50);
lv_obj_set_x( ui_yesButton, -65 );
lv_obj_set_y( ui_yesButton, 52 );
lv_obj_set_align( ui_yesButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_yesButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_yesButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_yesButton, lv_color_hex(0x0F71BE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_yesButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_yesText = lv_label_create(ui_yesButton);
lv_obj_set_width( ui_yesText, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_yesText, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_yesText, LV_ALIGN_CENTER );
lv_label_set_text(ui_yesText,"Yes");
lv_obj_set_style_text_font(ui_yesText, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_noButton = lv_btn_create(ui_demoScreen8);
lv_obj_set_width( ui_noButton, 100);
lv_obj_set_height( ui_noButton, 50);
lv_obj_set_x( ui_noButton, 73 );
lv_obj_set_y( ui_noButton, 53 );
lv_obj_set_align( ui_noButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_noButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_noButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_noButton, lv_color_hex(0x28A2E9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_noButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_noText = lv_label_create(ui_noButton);
lv_obj_set_width( ui_noText, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_noText, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_noText, LV_ALIGN_CENTER );
lv_label_set_text(ui_noText,"No");
lv_obj_set_style_text_font(ui_noText, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label4 = lv_label_create(ui_demoScreen8);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );

lv_obj_add_event_cb(ui_yesButton, ui_event_yesButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_noButton, ui_event_noButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_demoScreen8, ui_event_demoScreen8, LV_EVENT_ALL, NULL);

}
