// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: indicator_app

#include "../ui.h"

void ui_mainScreen_screen_init(void)
{
ui_mainScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_mainScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_mainScreen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_mainScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_seeDemoButton = lv_btn_create(ui_mainScreen);
lv_obj_set_width( ui_seeDemoButton, 113);
lv_obj_set_height( ui_seeDemoButton, 50);
lv_obj_set_x( ui_seeDemoButton, -2 );
lv_obj_set_y( ui_seeDemoButton, 110 );
lv_obj_set_align( ui_seeDemoButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_seeDemoButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_seeDemoButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_seeDemoButton, lv_color_hex(0x0F71BE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_seeDemoButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_seeDemo = lv_label_create(ui_seeDemoButton);
lv_obj_set_width( ui_seeDemo, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_seeDemo, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_seeDemo, LV_ALIGN_CENTER );
lv_label_set_text(ui_seeDemo,"See Demo");
lv_obj_set_style_text_font(ui_seeDemo, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_welcomeToDefang = lv_label_create(ui_mainScreen);
lv_obj_set_width( ui_welcomeToDefang, LV_SIZE_CONTENT);  /// 2
lv_obj_set_height( ui_welcomeToDefang, LV_SIZE_CONTENT);   /// 2
lv_obj_set_x( ui_welcomeToDefang, 6 );
lv_obj_set_y( ui_welcomeToDefang, 28 );
lv_obj_set_align( ui_welcomeToDefang, LV_ALIGN_CENTER );
lv_label_set_text(ui_welcomeToDefang,"Welcome to Defang!");
lv_obj_set_style_text_color(ui_welcomeToDefang, lv_color_hex(0x0F71BE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_welcomeToDefang, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_welcomeToDefang, &lv_font_montserrat_30, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_zoom(ui_welcomeToDefang, 256, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_logoSmall = lv_img_create(ui_mainScreen);
lv_img_set_src(ui_logoSmall, &ui_img_1452681969);
lv_obj_set_width( ui_logoSmall, LV_SIZE_CONTENT);  /// 507
lv_obj_set_height( ui_logoSmall, LV_SIZE_CONTENT);   /// 503
lv_obj_set_x( ui_logoSmall, -1 );
lv_obj_set_y( ui_logoSmall, -81 );
lv_obj_set_align( ui_logoSmall, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_logoSmall, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_logoSmall, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_logoSmall,65);

lv_obj_add_event_cb(ui_seeDemoButton, ui_event_seeDemoButton, LV_EVENT_ALL, NULL);

}
