// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: indicator_app

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void movedown_Animation( lv_obj_t *TargetObject, int delay);


// SCREEN: ui_loading
void ui_loading_screen_init(void);
lv_obj_t *ui_loading;
lv_obj_t *ui_logo;
void ui_event_loadingButton( lv_event_t * e);
lv_obj_t *ui_loadingButton;


// SCREEN: ui_mainScreen
void ui_mainScreen_screen_init(void);
lv_obj_t *ui_mainScreen;
void ui_event_seeDemoButton( lv_event_t * e);
lv_obj_t *ui_seeDemoButton;
lv_obj_t *ui_seeDemo;
lv_obj_t *ui_welcomeToDefang;
lv_obj_t *ui_logoSmall;


// SCREEN: ui_demoScreen
void ui_demoScreen_screen_init(void);
lv_obj_t *ui_demoScreen;
void ui_event_keyboard( lv_event_t * e);
lv_obj_t *ui_keyboard;
lv_obj_t *ui_letsGetStarted;
lv_obj_t *ui_enterNameArea;


// SCREEN: ui_demoScreen2
void ui_demoScreen2_screen_init(void);
void ui_event_demoScreen2( lv_event_t * e);
lv_obj_t *ui_demoScreen2;


// SCREEN: ui_demoScreen3
void ui_demoScreen3_screen_init(void);
void ui_event_demoScreen3( lv_event_t * e);
lv_obj_t *ui_demoScreen3;
lv_obj_t *ui_bar0;


// SCREEN: ui_demoScreen4
void ui_demoScreen4_screen_init(void);
void ui_event_demoScreen4( lv_event_t * e);
lv_obj_t *ui_demoScreen4;
lv_obj_t *ui_bar25;


// SCREEN: ui_demoScreen5
void ui_demoScreen5_screen_init(void);
void ui_event_demoScreen5( lv_event_t * e);
lv_obj_t *ui_demoScreen5;
lv_obj_t *ui_bar50;


// SCREEN: ui_demoScreen6
void ui_demoScreen6_screen_init(void);
void ui_event_demoScreen6( lv_event_t * e);
lv_obj_t *ui_demoScreen6;
lv_obj_t *ui_bar75;


// SCREEN: ui_demoScreen7
void ui_demoScreen7_screen_init(void);
void ui_event_demoScreen7( lv_event_t * e);
lv_obj_t *ui_demoScreen7;


// SCREEN: ui_demoScreen8
void ui_demoScreen8_screen_init(void);
void ui_event_demoScreen8( lv_event_t * e);
lv_obj_t *ui_demoScreen8;
lv_obj_t *ui_cloudComputing;
void ui_event_yesButton( lv_event_t * e);
lv_obj_t *ui_yesButton;
lv_obj_t *ui_yesText;
void ui_event_noButton( lv_event_t * e);
lv_obj_t *ui_noButton;
lv_obj_t *ui_noText;
lv_obj_t *ui_Label4;


// SCREEN: ui_demoScreen9
void ui_demoScreen9_screen_init(void);
lv_obj_t *ui_demoScreen9;
lv_obj_t *ui_solution;
void ui_event_interestedButton( lv_event_t * e);
lv_obj_t *ui_interestedButton;
lv_obj_t *ui_showMeAlready;


// SCREEN: ui_demoScreen10
void ui_demoScreen10_screen_init(void);
void ui_event_demoScreen10( lv_event_t * e);
lv_obj_t *ui_demoScreen10;
lv_obj_t *ui_yourName;
lv_obj_t *ui_heardOf;
lv_obj_t *ui_yesButton2;
lv_obj_t *ui_yesText2;
lv_obj_t *ui_Button2;
lv_obj_t *ui_noText2;


// SCREEN: ui_demoScreen11
void ui_demoScreen11_screen_init(void);
lv_obj_t *ui_demoScreen11;
lv_obj_t *ui____initial_actions0;
const lv_img_dsc_t *ui_imgset_769984564[1] = {&ui_img_1452681969};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void movedown_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 500);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y );
lv_anim_set_values(&PropertyAnimation_0, 0, 300 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_y );
lv_anim_start(&PropertyAnimation_0);
ui_anim_user_data_t *PropertyAnimation_1_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_1_user_data->target = TargetObject;
PropertyAnimation_1_user_data->val = -1;
lv_anim_t PropertyAnimation_1;
lv_anim_init(&PropertyAnimation_1);
lv_anim_set_time(&PropertyAnimation_1, 800);
lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_opacity );
lv_anim_set_values(&PropertyAnimation_1, 0, 255 );
lv_anim_set_path_cb( &PropertyAnimation_1, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_1, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_1, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_1, 0);
lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
lv_anim_set_early_apply( &PropertyAnimation_1, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_1, &_ui_anim_callback_get_opacity );
lv_anim_start(&PropertyAnimation_1);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_loadingButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_mainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_mainScreen_screen_init);
}
}
void ui_event_seeDemoButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_demoScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_demoScreen_screen_init);
}
}
void ui_event_keyboard( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_READY) {
      movedown_Animation(ui_keyboard, 0);
      _ui_screen_change( &ui_demoScreen2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_demoScreen2_screen_init);
}
}
void ui_event_demoScreen2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_SCREEN_LOADED) {
      _ui_screen_change( &ui_demoScreen3, LV_SCR_LOAD_ANIM_FADE_ON, 200, 100, &ui_demoScreen3_screen_init);
}
}
void ui_event_demoScreen3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_SCREEN_LOADED) {
      _ui_screen_change( &ui_demoScreen4, LV_SCR_LOAD_ANIM_FADE_ON, 200, 100, &ui_demoScreen4_screen_init);
}
}
void ui_event_demoScreen4( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_SCREEN_LOADED) {
      _ui_screen_change( &ui_demoScreen5, LV_SCR_LOAD_ANIM_FADE_ON, 200, 100, &ui_demoScreen5_screen_init);
}
}
void ui_event_demoScreen5( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_SCREEN_LOADED) {
      _ui_screen_change( &ui_demoScreen6, LV_SCR_LOAD_ANIM_FADE_ON, 150, 0, &ui_demoScreen6_screen_init);
}
}
void ui_event_demoScreen6( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_SCREEN_LOADED) {
      _ui_screen_change( &ui_demoScreen7, LV_SCR_LOAD_ANIM_FADE_ON, 200, 200, &ui_demoScreen7_screen_init);
}
}
void ui_event_demoScreen7( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_SCREEN_LOADED) {
      _ui_screen_change( &ui_demoScreen8, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_demoScreen8_screen_init);
}
}
void ui_event_demoScreen8( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_demoScreen9, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_demoScreen9_screen_init);
}
}
void ui_event_yesButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_demoScreen9, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_demoScreen9_screen_init);
}
}
void ui_event_noButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_demoScreen9, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_demoScreen9_screen_init);
}
}
void ui_event_interestedButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_demoScreen10, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_demoScreen10_screen_init);
      saveYourName( e );
}
}
void ui_event_demoScreen10( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_SCREEN_LOAD_START) {
      updateYourName( e );
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_loading_screen_init();
ui_mainScreen_screen_init();
ui_demoScreen_screen_init();
ui_demoScreen2_screen_init();
ui_demoScreen3_screen_init();
ui_demoScreen4_screen_init();
ui_demoScreen5_screen_init();
ui_demoScreen6_screen_init();
ui_demoScreen7_screen_init();
ui_demoScreen8_screen_init();
ui_demoScreen9_screen_init();
ui_demoScreen10_screen_init();
ui_demoScreen11_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_loading);
}
