// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: indicator_app

#ifndef _INDICATOR_APP_UI_H
#define _INDICATOR_APP_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

void movedown_Animation( lv_obj_t *TargetObject, int delay);
// SCREEN: ui_loading
void ui_loading_screen_init(void);
extern lv_obj_t *ui_loading;
extern lv_obj_t *ui_logo;
void ui_event_loadingButton( lv_event_t * e);
extern lv_obj_t *ui_loadingButton;
// SCREEN: ui_mainScreen
void ui_mainScreen_screen_init(void);
extern lv_obj_t *ui_mainScreen;
void ui_event_seeDemoButton( lv_event_t * e);
extern lv_obj_t *ui_seeDemoButton;
extern lv_obj_t *ui_seeDemo;
extern lv_obj_t *ui_welcomeToDefang;
extern lv_obj_t *ui_logoSmall;
// SCREEN: ui_demoScreen
void ui_demoScreen_screen_init(void);
extern lv_obj_t *ui_demoScreen;
void ui_event_keyboard( lv_event_t * e);
extern lv_obj_t *ui_keyboard;
extern lv_obj_t *ui_letsGetStarted;
extern lv_obj_t *ui_enterNameArea;
// SCREEN: ui_demoScreen2
void ui_demoScreen2_screen_init(void);
void ui_event_demoScreen2( lv_event_t * e);
extern lv_obj_t *ui_demoScreen2;
// SCREEN: ui_demoScreen3
void ui_demoScreen3_screen_init(void);
void ui_event_demoScreen3( lv_event_t * e);
extern lv_obj_t *ui_demoScreen3;
extern lv_obj_t *ui_bar0;
// SCREEN: ui_demoScreen4
void ui_demoScreen4_screen_init(void);
void ui_event_demoScreen4( lv_event_t * e);
extern lv_obj_t *ui_demoScreen4;
extern lv_obj_t *ui_bar25;
// SCREEN: ui_demoScreen5
void ui_demoScreen5_screen_init(void);
void ui_event_demoScreen5( lv_event_t * e);
extern lv_obj_t *ui_demoScreen5;
extern lv_obj_t *ui_bar50;
// SCREEN: ui_demoScreen6
void ui_demoScreen6_screen_init(void);
void ui_event_demoScreen6( lv_event_t * e);
extern lv_obj_t *ui_demoScreen6;
extern lv_obj_t *ui_bar75;
// SCREEN: ui_demoScreen7
void ui_demoScreen7_screen_init(void);
void ui_event_demoScreen7( lv_event_t * e);
extern lv_obj_t *ui_demoScreen7;
// SCREEN: ui_demoScreen8
void ui_demoScreen8_screen_init(void);
void ui_event_demoScreen8( lv_event_t * e);
extern lv_obj_t *ui_demoScreen8;
extern lv_obj_t *ui_cloudComputing;
void ui_event_yesButton( lv_event_t * e);
extern lv_obj_t *ui_yesButton;
extern lv_obj_t *ui_yesText;
void ui_event_noButton( lv_event_t * e);
extern lv_obj_t *ui_noButton;
extern lv_obj_t *ui_noText;
extern lv_obj_t *ui_Label4;
// SCREEN: ui_demoScreen9
void ui_demoScreen9_screen_init(void);
extern lv_obj_t *ui_demoScreen9;
extern lv_obj_t *ui_solution;
void ui_event_interestedButton( lv_event_t * e);
extern lv_obj_t *ui_interestedButton;
extern lv_obj_t *ui_showMeAlready;
// SCREEN: ui_demoScreen10
void ui_demoScreen10_screen_init(void);
void ui_event_demoScreen10( lv_event_t * e);
extern lv_obj_t *ui_demoScreen10;
extern lv_obj_t *ui_yourName;
extern lv_obj_t *ui_heardOf;
extern lv_obj_t *ui_yesButton2;
extern lv_obj_t *ui_yesText2;
extern lv_obj_t *ui_Button2;
extern lv_obj_t *ui_noText2;
// SCREEN: ui_demoScreen11
void ui_demoScreen11_screen_init(void);
extern lv_obj_t *ui_demoScreen11;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_1452681969);   // assets/Screenshot 2024-09-06 at 11.54.24 AM.png




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
