// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: indicator_app

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void saveYourName(lv_event_t * e);
void updateYourName(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
