// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: indicator_app

#include "ui.h"

const char * txt = "";

void saveYourName(lv_event_t * e)
{
	txt = lv_textarea_get_text(ui_enterNameArea);
}

//update the UI yourName label with the user inputted name
void updateYourName(lv_event_t * e) 
{
	lv_label_set_text(ui_yourName, txt);
}
